/** @jsxImportSource @emotion/react */
import { css } from '@emotion/react'
import styled from '@emotion/styled'
import Head from 'next/head'
import Link from 'next/link'

const Join = styled.div`
  width: 80%;
  max-width: 400px;
  margin: 30px auto;
  text-align: center;
  border: 1px solid gray;
  border-radius: 10px;
  padding: 30px 10px;
  > * {
    margin: 8px;
  }
  p {
    margin-bottom: 20px;
    font-weight: 300;
  }
  button {
    padding: 5px;
  }
`

export default function Home(title, description) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Join>
        <h3>Welcome to the Symptom Tracker App</h3>
        <p>Log in or sign up to start monitoring your health.</p>
        <button>Log In</button>
        <button>Sign Up</button>
      </Join>
    </div>
  )
}

export async function getStaticProps() {
  return  {
      props: {
          title: "Symptom Tracker Home",
          description: "Home page for symptom tracker app"
      }
  }
}