import Head from 'next/head'
import Link from 'next/link'

export default function Home(title, description) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h3>Log in or Sign Up</h3>
        <button>Log In</button>
        <button>Sign Up</button>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  return  {
      props: {
          title: "Symptom Tracker Home",
          description: "Home page for symptom tracker app"
      }
  }
}